# Utilise une image Python avec les librairies systèmes nécessaires pour l'OCR
FROM python:3.11-slim

# Installe les dépendances système pour PaddleOCR (Très important !)
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# Copie le code de tes collègues dans le conteneur
WORKDIR /app
COPY . .

# Installe les librairies Python de l'OCR
RUN pip install --no-cache-dir -r requirements.txt

# Lance l'API sur le port 8000
CMD ["python", "api.py"]